### ISSUE TITLE
Cannot read property 'facebookPermissionsType' of undefined.

### ISSUE THREAD

**Issue by xavicolomer** [xxsnakerxx/react-native-social-auth#10]
Hi there!

I am getting this error:
**Cannot read property 'facebookPermissionsType' of undefined.**

At this line:
`SocialAuth.facebookPermissionsType = RNSocialAuthManager.facebookPermissionsType;`

My guess is that I should bind some libraries and add the *.xcodeproj to mine. But Im not sure which ones.

Any ideas? 

Thanks!

**Comment by xxsnakerxx** [comment]
@xavicolomer are you sure that you done [this](https://github.com/xxsnakerxx/react-native-social-auth/tree/master/ios#readme)? And what version of react native?

**Comment by xavicolomer** [comment]
Hi there @xxsnakerxx 

First, thank you and good work.

I followed the steps again it kind'a work.

I had to solve this issue though 
https://github.com/weflex/react-native-wechat/issues/33
