### ISSUE TITLE
Facebook authorization without React-Native-WebView

### ISSUE THREAD

**Issue by Mactub07** [xxsnakerxx/react-native-social-auth#5]
is there a way to authorize app without WebView? for example if user has facebook app in own device, we just redirect to facebook app and then authorize?

**Comment by xxsnakerxx** [comment]
Hi! It's default SDK behavior 
- ios https://github.com/facebook/facebook-ios-sdk/blob/master/FBSDKLoginKit/FBSDKLoginKit/FBSDKLoginManager.h#L78 
- android https://developers.facebook.com/docs/reference/android/current/class/LoginBehavior/

**Comment by Mactub07** [comment]
Hello, Yes, I see, but it still open WebView instead native FB-app, use platform IOS > 10

**Comment by xxsnakerxx** [comment]
I published the new version! Try it, maybe SDK was outdated

**Comment by Mactub07** [comment]
yes, I see , webView is opened faster then before(new FB SDK), but it still open WebView :((

**Comment by xxsnakerxx** [comment]
Is there any logs in xcode console?

**Comment by xxsnakerxx** [comment]
and check you `plist` file

```xml
<key>LSApplicationQueriesSchemes</key>
<array>
		<string>fbauth</string>
		<string>fbauth2</string>
</array>
```

Both keys must exist

**Comment by xxsnakerxx** [comment]
@Mactub07 Does it work?

**Comment by Mactub07** [comment]
I tested, It didn't help

**Comment by Mactub07** [comment]
mistake in console when close webview "Warning: Attempt to present <UIAlertController: 0x101273ea0> on <FBSDKContainerViewController: 0x1012778d0> whose view is not in the window hierarchy!" may be this can help

**Comment by xxsnakerxx** [comment]
The error is just about presenting RN Alert component

**Comment by xxsnakerxx** [comment]
Try to add `fb` sceme

```xml
<key>LSApplicationQueriesSchemes</key>
    <array>
        <string>fb</string>
    </array>
```

**Comment by Mactub07** [comment]
will try the same :) http://stackoverflow.com/questions/32566734/native-facebook-app-does-not-open-with-facebook-login-in-ios-9

**Comment by xxsnakerxx** [comment]
Hm... I found this https://developers.facebook.com/blog/post/2015/10/29/Facebook-Login-iOS9/ 

So, it's default behavior at all (for >=iOS9)

**Comment by Mactub07** [comment]
btw , <string>fb</string> also don't help
