### ISSUE TITLE
Blank page in WebView

### ISSUE THREAD

**Issue by sathyakumarseshachalam** [xxsnakerxx/react-native-social-auth#6]
Installed Facebook SDK. I am just trying to do whatever's in the example

```
SocialAuth.getFacebookCredentials(["email", "user_friends"], SocialAuth.facebookPermissionsType.read)
                  .then((credentials) => console.log(credentials))
                  .catch((error) => console.log(error));
```

However the promise is never resolved. And the webview post all authorization ends up being a blank page as below. Clicking on "Done" results in cancel request
` {message: "Credentials request was canceled", cancelled: true, code: -1}`

Note that example works just fine. But am not able to figure the correct misconfiguration (or lack of proper configuration)

![simulator screen shot 26-nov-2016 6 00 21 pm](https://cloud.githubusercontent.com/assets/16410676/21013712/264e35fc-bd81-11e6-8260-02eeef917474.png)

**Comment by xxsnakerxx** [comment]
Are there any logs in XCode console?

**Comment by sathyakumarseshachalam** [comment]
I do have some errors in there like 
```
2016-12-09 06:13:29.757 XXXX[61829:8555589] -canOpenURL: failed for URL: "fbauth2:/" - error: "The operation couldn’t be completed. (OSStatus error -10814.)"
2016-12-09 06:13:29.759 XXXX[61829:8555589] -canOpenURL: failed for URL: "fbauth2:/" - error: "The operation couldn’t be completed. (OSStatus error -10814.)"
```

And

```
__nw_socket_service_writes_block_invoke sendmsg(fd 9, 31 bytes): socket has been closed
2016-12-09 06:13:36.670958 XXXX[61829:8574160] [] nw_endpoint_flow_protocol_error [15.1 157.240.7.20:443 cancelled socket-flow (null)] Socket protocol sent error: [32] Broken pipe
2016-12-09 06:13:36.671154 XXXX[61829:8574160] [] nw_endpoint_flow_protocol_disconnected [15.1 157.240.7.20:443 cancelled socket-flow (null)] Output protocol disconnected

```

Attaching the full logs here.  (Removed the startup logs, Just posting the portion after app has launched)
[xcode-logs.TXT](https://github.com/xxsnakerxx/react-native-social-auth/files/640939/xcode-logs.TXT)

**Comment by xxsnakerxx** [comment]
Check your `info.plist`

```xml
<key>CFBundleURLTypes</key>
<array>
  <dict>
    <key>CFBundleURLSchemes</key>
    <array>
      <string>fb{your-app-id}</string>
    </array>
  </dict>
</array>
<key>LSApplicationQueriesSchemes</key>
<array>
  <string>fbauth2</string>
</array>
// use setFacebookApp({id, name}) before login
// or add these lines
<key>FacebookAppID</key>
<string>{your-app-id}</string>
<key>FacebookDisplayName</key>
<string>{your-app-name}</string>
```

**Comment by sathyakumarseshachalam** [comment]
I seem to have all of the above and more
```
<key>CFBundleURLTypes</key>
    <array>
      <dict>
        <key>CFBundleURLSchemes</key>
        <array>
          <string>fb{my app id}</string>
        </array>
      </dict>
    </array>
    <key>FacebookAppID</key>
    <string>{my app id}</string>
    <key>FacebookDisplayName</key>
    <string>{my app name}</string>
    <key>LSApplicationQueriesSchemes</key>
    <array>
      <string>fbapi</string>
      <string>fb-messenger-api</string>
      <string>fbauth2</string>
      <string>fbshareextension</string>
    </array>
```

**Comment by sathyakumarseshachalam** [comment]
This [link](https://forums.developer.apple.com/thread/50332) talks about the problem, but am not conversant with Swift or IOS development to even understand what this means. I was using SDK version 4.17, but now I just copied SDK from this project. Still no luck

**Comment by xxsnakerxx** [comment]
Try to add [this](https://github.com/xxsnakerxx/react-native-social-auth/blob/master/example/ios/socialAuthExample/Info.plist#L42-L46) into plist

or as described here https://forums.developer.apple.com/thread/50332#184417 (plist part)

**Comment by xxsnakerxx** [comment]
Also look at  [here](https://github.com/xxsnakerxx/react-native-social-auth/blob/master/example/ios/socialAuthExample/AppDelegate.m#L36) and [here](https://github.com/xxsnakerxx/react-native-social-auth/blob/master/example/ios/socialAuthExample/AppDelegate.m#L41-L44)

**Comment by sathyakumarseshachalam** [comment]
Awesome. Thank you. The last two changes did the trick - authentication is successful and am able to get back a response. Is this something thats there in the README that  I missed ? I did `react-native link` after npm installing

**Comment by xxsnakerxx** [comment]
Docs about modifying AppDelegate there is in [iOS part](https://github.com/xxsnakerxx/react-native-social-auth/tree/master/ios#facebook)
