### ISSUE TITLE
iOS - framework not found error

### ISSUE THREAD

**Issue by UltCombo** [xxsnakerxx/react-native-social-auth#7]
Hello.

I've installed `react-native-social-auth@0.5.8` from npm, linked it to a fresh project with `react-native link`, added `RNSocialAuth.xcodeproj` to my project libraries and made sure that `libRNSocialAuth.a` was added to the "Link Binary With Libraries" Build Phase (everything according to the [iOS setup doc](https://github.com/xxsnakerxx/react-native-social-auth/tree/master/ios#readme)).

Now when I try to run the project on my iPhone 7 device, I get the following error:

> ld: framework not found FBSDKLoginKit for architecture arm64

If I move the `libRNSocialAuth.a` to the top of the "Link Binary With Libraries" list, then I get:

> ld: framework not found Bolts for architecture arm64

If I try to run it in iPhone 6 simulator, then I get:

> ld: framework not found FBSDKCoreKit for architecture x86_64

I'm not sure if this is a problem with the package or if I'm doing something wrong. Any ideas?

**Comment by UltCombo** [comment]
Oh, I needed to add the Frameworks and `Framework Search Paths` listed in the "Facebook" section in order to get the app to compile.

My bad.

**Comment by Luckygirlllll** [comment]
@UltCombo I have the same problem, how did you add Framework?

**Comment by UltCombo** [comment]
Hello @Luckygirlllll, if I recall correctly you have to follow the instructions in the [iOS setup](https://github.com/xxsnakerxx/react-native-social-auth/tree/master/ios#readme). Note that you need to set up Facebook even if you are only using Twitter auth, that was the problem when I tried to install it a year ago.
